name: Demo trigger events

on:
  # Webhook events
  push:
    branches:
      - main
      - feat/*
  pull_request: 
    branches:
      - main
  issues:
    types:
      - opened
      - closed
  
  # Scheduled events
  schedule:
    - cron: 0 0 * * *
    - cron: 0 9 * * 0
    
  # Manual events
  workflow_dispatch: 
    inputs:
      yourName:
        required: true
        default: My friend
      areYouFeelingGood:
        required: true
        type: boolean
      howDoYouFindGithubActions:
        required: false
        type: choice
        options:
          - Awesome
          - Okay
          - Na

env:
  MY_NAME: Nico
  GREETING: Hello
  
jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeting step (expectation: Hello Nico)"
        run: echo $GREETING $MY_NAME
  Greeting2:
    runs-on: ubuntu-latest
    env:
      GREETING: Good morning
    steps:
      - name: "Greeting step (expectation: Good morning Nico)"
        run: echo $GREETING $MY_NAME
      - name: "Greeting step (expectation: Good afternoon Nico)"
        run: echo $GREETING $MY_NAME
        env:
          GREETING: Good afternoon
  Job2:
    runs-on: ubuntu-latest
    needs: [Greeting]
    steps:
      - name: Step2
        run: echo "${{ github.actor }} is learning Github Actions"
      - name: Step3
        run: echo "Great!"
        if: ${{inputs.areYouFeelingGood}}
      - name: Step4
        run: echo "No worries, I am here with you!"
        if: ${{inputs.areYouFeelingGood == false}}
        
